#!/system/bin/sh

//ZRAM Specific configs


echo /dev/sda38 > /sys/block/zram0/backing_dev
echo all > /sys/block/zram0/idle
echo zstd > /sys/block/zram0/comp_algorithm
echo 2G > /sys/block/zram0/disksize
echo 2G > /sys/block/zram0/mem_limit


MB_SHIFT=20
4K_SHIFT=12
echo $((400<<MB_SHIFT>>4K_SHIFT)) > \/sys/block/zram0/writeback_limit.
echo 1 > /sys/block/zram0/writeback_limit_enable




//Screen Cast and Shealth Fix
resetprop ro.config.tima 0
resetprop ro.config.iccc_version iccc_disabled
resetprop wlan.wfd.hdcp disable
